<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * QueryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QueryRepository extends EntityRepository
{
    
    public function getRecentQueryByText($text, $ttl) 
    {
        $results = $this->getEntityManager()
        ->createQuery('SELECT q FROM AppBundle:Query q WHERE q.createdOn >= :ttl ORDER BY q.createdOn ASC')
        ->setParameter('ttl', new \DateTime('-'. $ttl . ' seconds'))
        ->getResult();
        
        return current($results);
    }
}
